### ISSUE TITLE
What is the run order?

### ISSUE THREAD

**Issue by Oleg26Dev** [eirikb/Netro#1]
Hi, thank you for the Netro.
What is the order for running the Netro in the type: reverse tunnel?
On what computer Netro should be run first? Accordingly to your  description:
1. Netro A listens for incoming connections, and listens for reverse tunneling.
2. Netro B connects to A for tunneling.
3. When a client connects to A the data will be transferred through the link between A and B.
4. Connection is made on B to desired host:port.

**Comment by eirikb** [comment]
On the one where you run Netro A.
But you should probably look for some alternative to Netro, perhaps something with support for encryption.

**Comment by Oleg26Dev** [comment]
I did not find any alternatives implemented in .NET.
What I need: it is the reversing tunnel functionality.

There is what I need for my task:
https://github.com/sailro/Bdtunnel

But it has no reverse tunnel functionality, i.e.: to have possibility to work with computers behind of firewalls.
I am searching .NET implementation to add it to the Bdtunnel.
The idea is: 
B  is a local computer with my WCF service working with database server, I can change it to some B1, B2 etc
A is the cloud computer, to which remote clients connect running the WCF clients. They do not know where is the real WCF service and db.
By fact clients work with my local WCF and database at B

**Comment by eirikb** [comment]
Why must the service for tunneling be .NET? Surely it doesn't have to be part of your software, you could just run it alongside what you already have.

**Comment by Oleg26Dev** [comment]
Right question.
I have cloned the https://github.com/sailro/Bdtunnel to have a possibility to forward set of input addresses to a set of output addresses, it works ok and does what I need. The Bdtunnel client connects to the server only one way, but I'd like to add yet another possibility: server connects to the client and then client works with the server, i.e. to work with server behind of firewall as you described. 
That is why I want to add this kind of reverse connection, embed it to the Bdtunnel, it will be "all in one" and ""entities should not be multiplied beyond necessity".

**Comment by Oleg26Dev** [comment]
I ran the Netro in your edition, the reverse tunnel  works. Great! Thank you.

Need to review and improve the logic for auto-reconnection when client or server was crashed and the restarted etc.

**Comment by eirikb** [comment]
If you make an improvement to Netro, e.g., persistent connection, it could be nice to get a PR.  
Another thing which would actually make Netro usable (IMHO) is encryption. Could just use Netro.exe to create a key pair, like ssh-keyken, just without the hassle to have any external tools.
